name: 'pipeline_01'
version: '1.0.0'

profile: 'pipeline_01'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  pipeline_01:
    staging:
      schema: staging
      +materialized: table
      tags: ['staging']
    
    intermediate: 
      +materialized: ephemeral
      tags: ['intermediate']
    
    marts:
      schema: marts
      +materialized: table
      tags: ['marts']

seeds:
  pipeline_01:
    +schema: seeds
    tags: ['seed']
