pipeline_01:
  outputs:
    dev:
      type: sqlserver
      driver: ODBC Driver 17 for SQL Server 
      server: localhost\SQL2019EXPRESS
      database: AdventureWorks2019
      schema: Sales
      windows_login: true
      trust_cert: true
      threads: 1
  target: dev
