version: 2

sources:
  - name: AdventureWorks2019
    description: Dados da microsoft
    schema: Sales
    tables:
      - name: SalesOrderDetail
        description: Tabela de vendas
        columns:
          - name: SalesOrderID
            description: Identificador único do produto
            tests: [not_null]
          - name: OrderQty
            description: Quantidade
            tests: [not_null]
          - name: UnitPrice
            description: Preço da unidade
            tests: [not_null]
      - name: SalesOrderHeader
        description: cabeçalho de vendas
        columns:
          - name: SalesOrderID
            description: Identificador único do produto
            tests: [not_null,unique]
          - name: OrderDate
            description: Data de compra
            tests: [not_null]
          - name: ShipDate
            description: Data de envio
            tests: [not_null]
          - name: TotalDue
            description: valor total da compra
          - name: SubTotal
            description: SubTotal
            tests: [not_null]
          - name: TaxAmt
            description: imposto
          - name: Freight
            description: Frete