version: 2

sources:
  - name: AdventureWorks_Sales
    description: Dados da Microsoft - schema Sales
    schema: Sales
    tables:
      - name: SalesOrderDetail
        description: Tabela de vendas
        columns:
          - name: SalesOrderID
            description: Identificador único do produto
            tests: [not_null]
          - name: OrderQty
            description: Quantidade
            tests: [not_null]
          - name: UnitPrice
            description: Preço da unidade
            tests: [not_null]
          - name: ProductID
            description: ID do produto
            tests: [not_null, unique]
          - name: Name
            description: nome do produto
            tests: [not_null,unique]
      - name: SalesOrderHeader
        description: Cabeçalho de vendas
        columns:
          - name: SalesOrderID
            description: Identificador único do produto
            tests: [not_null, unique]
          - name: OrderDate
            description: Data de compra
            tests: [not_null]
          - name: ShipDate
            description: Data de envio
            tests: [not_null]
          - name: TotalDue
            description: Valor total da compra
          - name: SubTotal
            description: SubTotal
            tests: [not_null]
          - name: TaxAmt
            description: Imposto
          - name: Freight
            description: Frete
            tests: [not_null]
          - name: ProductID
            description: ID do produto
            tests: [not_null, unique]
          - name: Name
            description: Nome do produto
            tests: [not_null, unique]

  - name: AdventureWorks_Production
    description: Dados da Microsoft - schema Production
    schema: Production
    tables:
      - name: Product
        description: Produtos
        columns:
          - name: ProductID
            description: ID do produto
            tests: [not_null, unique]
          - name: Name
            description: Nome
            tests: [not_null, unique]
          - name: ProductSubcategoryID
            description: ID da categoria 
            tests: [not null, unique]
      - name: ProductSubcategory
        description: Subcategoria de produtos
        columns:
          - name: Name
            description: Nome
            tests: [not_null, unique]
          - name: ProductSubcategoryID
            description: ID da categoria
            tests: [not_null,unique]
          - name: ProductCategoryID
            description: ID da categoria
            tests: [not_null, unique]
      - name: ProductCategory
        description: Categoria de Produtos
        columns:
          - name: ProductCategoryID
            description: ID da categoria
            tests: [not_null, unique]
          - name: Name
            description: Nome da categoria
            tests: [not_null,unique]
